# Project urls

link_1 = "http://suninjuly.github.io/simple_form_find_task.html"
link_2 = "http://suninjuly.github.io/huge_form.html"
link_3 = "http://suninjuly.github.io/find_xpath_form"
link_4 = "http://suninjuly.github.io/find_xpath_form"
link_5 = "http://suninjuly.github.io/registration2.html"
link_6 = "https://suninjuly.github.io/math.html"
link_7 = "http://suninjuly.github.io/get_attribute.html"
link_8 = "http://suninjuly.github.io/selects1.html"
link_9 = "https://SunInJuly.github.io/execute_script.html"
link_10 = "https://SunInJuly.github.io/execute_script.html"
link_11 = "http://suninjuly.github.io/file_input.html"
link_12 = "http://suninjuly.github.io/alert_accept.html"
link_13 = "http://suninjuly.github.io/redirect_accept.html"
link_14 = "http://suninjuly.github.io/wait1.html"
link_15 = "http://suninjuly.github.io/explicit_wait2.html"